lesson_names = [
    'Algebra',
    'Geometry',
    'Statistics',
    'Literature',
    'Geography',
    'Literature',
    'Reading',
    'Physics',
    'Music',
    'History',
    'Writing',
    'Math',
    'Math',
    'English',
    'Nature',
    'Music',
    'Writing or Composition',
    'Speech',
    'Biology',
    'Chemistry',
    'French',
    'German',
    'Psychology',
    'Art',
]

time_ranges = [
    {'start': '07:00', 'end': '08:00'},
    {'start': '09:00', 'end': '09:30'},
    {'start': '10:00', 'end': '10:30'},
    {'start': '10:30', 'end': '11:15'},
    {'start': '11:30', 'end': '12:15'},
    {'start': '13:00', 'end': '13:45'},
    {'start': '14:00', 'end': '14:45'},
    {'start': '15:00', 'end': '15:30'},
]