Screen:
    name: "add_homework"
    BoxLayout:
        id: add_homework_layout
        orientation: 'vertical'
        MDToolbar:
            id: add_homework_top_toolbar
            title: "Select Date / Schedule / Lesson"
            elevation: 8
        ScrollView:
            MDBoxLayout:
                orientation: "vertical"
#                padding: dp(48)
#                spacing: 10
                size_hint_y: None
                height: self.minimum_height

                MDStackLayout:
                    adaptive_size: True
#                    pos_hint: {"center_x": 1}
                    spacing: dp(12)
                    size_hint: (1, None)
                    MDRoundFlatIconButton:
                        id: add_homework_date
                        _radius: dp(5)
                        icon: "calendar"
                        text: "2020-12-20"
                        spacing: dp(12)
    #                        font_name: app.get_app_font()
                        on_release: None

                MDSeparator:

                MDStackLayout:
                    id: add_homework_schedules_wrapper
                    adaptive_size: True
                    pos_hint: {"center_x": .5}
                    spacing: dp(12)
                    size_hint: (1, None)

                    RoundFlatToggleButton:
                        text: "Demo 1"
                        icon: "view-list"
                        group: "schedule"
                    RoundFlatToggleButton:
                        text: "Demo 2"
                        icon: "view-list"
                        group: "schedule"

                MDSeparator:

                StackLayout:
                    id: add_homework_lessons_wrapper
                    adaptive_size: True
                    pos_hint: {"center_x": .5, "center_y": .5}
                    spacing: dp(12)
                    size_hint: (1, None)

                    RoundFlatToggleButton:
                        text: "Lesson 1"
                        icon: "book"
                        group: "lesson"
                    RoundFlatToggleButton:
                        text: "Lesson 2"
                        icon: "book"
                        group: "lesson"
                    RoundFlatToggleButton:
                        text: "Lesson 3"
                        icon: "book"
                        group: "lesson"

                MDSeparator:

                StackLayout:
                    adaptive_size: True
                    pos_hint: {"center_x": .5, "center_y": .5}
                    spacing: dp(12)
                    size_hint: (1, None)

                    MDRaisedButton:
                        id: add_homework_next_btn
                        text: "Proceed"
    #                        spacing: dp(12)
    #                        pos_hint: {"center_x": .5, "center_y": 1}
    #                        font_name: app.get_app_font()
                        on_release: None


<RoundFlatToggleButton@MDFillRoundFlatIconButton,MDToggleButton>:
    _radius: dp(5)
    ripple_alpha: 0