Screen:
    name: "add_lesson"
    BoxLayout:
        id: add_lesson_layout
#        orientation: 'vertical'
        size_hint_y: None
        height: root.height - add_lesson_top_toolbar.height

    AddLessonLayout:

    MDToolbar:
        id: add_lesson_top_toolbar
        title: "Add Lesson"
        elevation: 8
        pos_hint: {"top": 1}


<AddLessonLayout@ScrollView>:
    GridLayout:
        size_hint_y: None
        height: self.minimum_height
        spacing: "10dp"
        padding: "10dp"
        cols: 1

        Widget:
            size_hint_y: None
            height: app.theme_cls.standard_increment

        CardLessonTitle:

        CardDelTasks:
            id: edit_lesson_del_homeworks_card


<CardLessonTitle@BoxLayout>:
    orientation: "vertical"
    size_hint_y: None
    height: self.minimum_height
    padding: "10dp"
    spacing: "10dp"

    MDTextField:
        id: add_lesson_title
        hint_text: "Title"
        text_max: 50
#        fill_color: 0, 0, 0, 0
        mode: 'fill'
        helper_text_mode: "on_focus"
        helper_text: "maximum 50 chars length"




<CardDelTasks@BoxLayout>:
    orientation: "vertical"
    size_hint_y: None
    height: self.minimum_height
    padding: "10dp"
    spacing: "10dp"

    BoxLayout:
        size_hint_y: None
        height: self.minimum_height
        spacing: "5dp"

        MDLabel:
            id: note_label
            font_style: 'Caption'
            theme_text_color: 'Custom'
            text_color: app.theme_cls.accent_color
            text: "Note! Lesson has tasks assigned, use the option below to delete them on saving changes."


    BoxLayout:
        size_hint_y: None
        height: self.minimum_height
        spacing: "5dp"

        MDLabel:
            id: edit_lesson_del_homeworks_label
            font_style: 'Subtitle1'
            theme_text_color: 'Custom'
            text_color: app.theme_cls.primary_color
            text: "Delete related tasks"

        MDSwitch:
            id: edit_lesson_del_homeworks_switch
            active: False
